### PR TITLE
feat(mappings): leader doom reload and telesc reloader

### PR DESCRIPTION
**Pull request by molleweide**

### CODE REVIEW

**Comment by molleweide** [comment]
1. finally it works. This is how you do it from the commandline:

`gh pr create --base develop`

This command above creates a PR from the currently checked out local branch into upstream develop branch. nice!!
This makes it much easier to make PRs from commandline. Maybe I am late to the party?? 😄 

2. In this pr I added the builtin telescope reloader command so that one SHOULD be able to reload specific plugins
when working on them locally. HOWEVER, I only seem to be able to reload local plugins when I am working in the local plugins path. When I run the reloader command inside of doom-nvim dir I cant find my modules.

Could someone who is more experienced try to comment on this why this is not working. I think that the command is
good and should be brought into doom but it needs some help maybe. Or maybe the issue only arises for me on my own system? Could somebody other than m test this command and see if it works for you. If we get it to fully work it is a very handy mapping.

**Comment by connorgmeehan** [comment]
This is cool!  This would go really well with the docker test environment

**Comment by molleweide** [comment]
Nice!!

**Comment by molleweide** [comment]
I haven't had time to test the docker yet btw but im really looking fwd to try it out soon.

**Comment by molleweide** [comment]
I haven't had time to test the docker yet btw but im really looking fwd to try it out soon.

**Pull request closed without merging**
