### PR TITLE
[Fix] [`doom-dashboard.lua` #345]

### PR DESCRIPTION
**Pull request by cleong14**
(Bug Fixes) - changes made following [`dashboard-nvim`](https://github.com/glepnir/dashboard-nvim) Vimscript -> Lua rewrite

- add `local db = require("dashboard")`
- rewrite (Vimscript) `vim.g.dashboard_custom_section` -> (Lua) `db.custom_center`
- rewrite (Vimscript) `vim.g.dashboard_custom_footer` -> (Lua) `db.custom_footer`
- rewrite (Vimscript) `vim.g.dashboard_custom_header` -> (Lua) `db.custom_header`
- fix `custom_header` support for when user sets `config.doom.dashboard_custom_header`
- fix/update header colors (highlight groups)

### CODE REVIEW

**Comment by cleong14** [comment]
Hi @NTBBloodbath ,

I reviewed the failing check and it appears to be related to pre-existing code found here

https://github.com/NTBBloodbath/doom-nvim/blob/9e93d6d0e3c9d46909d1797d8ef49a005a02286a/lua/colors/doom-one/utils/init.lua#L88

and here

https://github.com/NTBBloodbath/doom-nvim/blob/9e93d6d0e3c9d46909d1797d8ef49a005a02286a/lua/colors/utils/init.lua#L88

Let me know how I may assist or how you'd like to proceed?

Thanks!

**Comment by NextAlone** [comment]
the lua dir structure has been modified

**Comment by connorgmeehan** [comment]
Just tested it all out, seems to be working well.  Thanks for the contribution!

**Comment by connorgmeehan** [comment]
Hey nextalone, it should be merged in #353

**Comment by NextAlone** [comment]
> Hey nextalone, it should be merged in #353

Oops forgot the pull request

**Comment by NextAlone** [comment]
> Hey nextalone, it should be merged in #353

Oops forgot the pull request

**Pull request merged**
