### PR TITLE
Assume ~/.config/nvim rather than ~/.config/doom-nvim in lua code

### PR DESCRIPTION
**Pull request by junkblocker**
For people wanting control over install locations, prefer the ~/.config/nvim location in lua code so it is easier to experiment with doom-nvim.
The install process can stay with ~/.config/doom-nvim.

### CODE REVIEW

**Comment by NTBBloodbath** [comment]
Hey, thank you. I think it makes sense because in the installation step the installer creates a symlink from `~/.config/doom-nvim` to `~/.config/nvim`.

However it may bring compatibility issues when using a configuration switcher like [cheovim](https://github.com/NTBBloodbath/cheovim) because it needs to be placed in `~/.config/nvim` to work. Maybe we can rethink this so we can retain the compatibility with such tool? :thinking:

**Comment by junkblocker** [comment]
I think the cheovim bit sounds like a non-sequiter unless you are saying `doom-nvim` configuration should only work if installed by `cheovim` or `doom-nvim` installer.

**Comment by NTBBloodbath** [comment]
woops, I think I should explain it a bit more, sorry.

Let's see, I'm meaning that if you are using cheovim for managing your Neovim configurations then the `~/.config/nvim` path will be used for cheovim and not for the `doom-nvim` files so there can be some errors while trying to use `doom-nvim` with `cheovim` with the changes that you've made. However I don't really have metrics about how many people uses `cheovim` with `doom-nvim` but anyway I think we should retain the compatibility with it.

> For people wanting control over install locations

So based in the above explanation, what about using a customizable path for achieving this? I mean, instead of pointing the `doom-nvim` path to `~/.config/doom-nvim` or `~/.config/nvim` in the Lua code we can maybe allow to point it to custom paths? So by example, someone can set a custom path like `~/Development/doom-nvim` and all the Lua code will point to that custom path. I don't know if it's okay for you or if I'm going a little too far :sweat_smile:

Other way that I'm thinking about can be maybe add a custom flag for cheovim users in the `doom-nvim` installer and then use `sed` over the files so we can re-point the paths to `~/.config/doom-nvim` and avoiding issues when using such tool. If that's the case then we can just merge this and do these changes later. Let me know what do you think about!

**Comment by junkblocker** [comment]
I fully understand your desire to keep this config compatible with your cheovim utility but it sounds like I am not your target audience. I have my own setup scripts for everything I ever set up and I try to avoid spending time learning yet another tool version selection/installer for a particular lanaguage/tool/devenv ecosystem for, often, marginal convenience and much mental overload (rvm, asdf, gvm, ansible etc.) when I can just script things myself with more finer grained control. So I'll just leave it here for now for you / cheovim / doom-nvim users to use or discard as you may wish.

**Comment by NTBBloodbath** [comment]
I think it's okay to merge this one, I really think it's a good idea to stick to `~/.config/nvim` as it should be. And as I've said before there's other solution for cheovim users because this one needs a different setup to work and I'll do these changes later but that's other thing.

Although I have a small request before giving merge, and it is to know if you could change the target branch to develop? Only hotfixes should go to main, thanks in advance!

**Comment by junkblocker** [comment]
Opened #41

**Comment by NTBBloodbath** [comment]
Thank you so much!

**Pull request closed without merging**
