### PR TITLE
[WIP] feat: Implemented new proposed modular architecture + config changes

### PR DESCRIPTION
**Pull request by connorgmeehan**
Changes:
- Restructured `doom_modules.lua` now organised just by `features`, `langs`, and an optional `user` category.
- Changes the concept of a module, now a single file that defines packages, config functions, settings, keybinds, commands and autocommands that adds some behaviour or capability.
  - Refactored all existing modules to this new format
- Refactored `doom_config.lua`, is now `config.lua` and can set the same settings imperatively using `doom` global object.
- Added helper functions `doom.use_package`, `doom.use_bind`, `doom.use_cmd`, `doom.use_autocmd` to add packages, binds, cmds and autocmds in `config.lua` file. (STILL WIP)
- Combined `formatter` and `linter` module (now just `linter`) -> uses null-ls.
- Added `lsp_progress` module: uses fidget.nvim to show LSP indexing/loading progress.
- Added `annotations` module: uses neogen to generate code annotations/documents.  Can anyone think of a better name?
  - Replaces broken `nvim-tree-docs` plugin that was installing by default 
- Refactored `kommentary` module, now `comments` (try to keep module name generic) uses `Comment.nvim` to generate comments.
- Implemented/reimplemented langs support for bash, c_sharp, config, cpp, css, glsl, go, haskell, java, javascript, kotlin, 
lua, markdown, python, rust, tailwindcss, teal, terraform, typescript, vue.
- **Please send any feedback my way!**

This PR is to track the final changes on the new modular architecture.  There are still a few tasks outstanding:
- Change `doom.use` to `doom.use_package`
- Add `doom.use_bind`, `doom.use_cmd`, `doom.use_autocmd` functions
- Cleanup and remove from history any files that shouldn't be in the PR.
- Rename `lua/doom/modules/core/` to `lua/doom/modules/internal/` (I think core makes more sense to refer to the doom nvim framework and internal makes more sense as the internal modules that allow doom nvim to work).
- **Please give any feedback.**

 Once it's merged:
- Help testing `doom.<option>` config options are working correctly. (@NTBBloodbath you might understand these best)
- Help testing module inter-dependencies are all working
- Help testing on different systems, in different environments

### CODE REVIEW

**Comment by molleweide** [comment]
I love the lsp progress spinner in the lower right

**Comment by molleweide** [comment]
Hey connor, what is the difference btw this branch and test-mod-arc?

**Comment by connorgmeehan** [comment]
@molleweide Good question!  Basically I'm keeping my own config in `test-module-architecture` and the PR in `feature/module-architecture-2`.  They're both in sync with each other through merges and cherry picks but this is the branch that will ultimately merge into doom-nvim.

**Comment by molleweide** [comment]
ok, ill switch to this later then!

**Comment by molleweide** [comment]
Connor do you get this every time you reload::

```
Do you need to configure your work environment as `LÖVE`?

Request Actions:
1. Apply and modify settings
2. Apply but do not modify settings
3. Don't show again
Type number and <Enter> or click with the mouse (q or empty cancels):
```

**Pull request merged**
