### PR TITLE
(next): moves `doom.settings` table into file in root dir.

### PR DESCRIPTION
**Pull request by molleweide**
@connorgmeehan 

I closed the previous `settings` PR and made a new one. This one is in sync with latest next.

1. adds `settings.lua` file in root so that it becomes easy/obvious for users where to set/change doom specific settings.
2. removes `settings` from `core/global_doom.lua`. 
my thought here is that since we specify defaults for each settings, it becomes more maintenance overhead to keep a duplicate default table in core. What are your thoughts on this. it is easy to add it back and do a `tbl_deep_extend` but now I opted for just removing the core table so that you only have the root table.
4. loads settings in `core/init.lua`
5. replaces all instances with the new `doom.settings...` prefix, in eg. `doom.settings.leader_key`.
  - `doom.logging` -> `doom.settings.logging` etc..

### CODE REVIEW

**Comment by molleweide** [comment]
fails for:   
```
lua/doom/modules/core/nest/init.lua:111:19: unused variable bufnr
Error: unused variable bufnr
```

**Comment by molleweide** [comment]
hey connor, why did you close this one?

**Comment by molleweide** [comment]
hey connor, may I ask why you closed this one?

**Comment by connorgmeehan** [comment]
It must have auto-closed when I deleted the `next` branch.  If you rebase this onto `main` I'm happy to review and merge :)

**Pull request closed without merging**
