### PR TITLE
refact: Move doom settings into its own table (`doom.settings`)

### PR DESCRIPTION
**Pull request by molleweide**
attempts to move all user changeable settings into `doom.settings`.
i also add a root file `settings.lua` for user overrides.

### CODE REVIEW

**Comment by molleweide** [comment]
i don't understand why the check fails.

**Comment by molleweide** [comment]
also i reloader or something should also be update now so that the user settings override global settings on change.
i haven't looked into that yet tho

**Comment by NTBBloodbath** [comment]
> i don't understand why the check fails.

Checks are failing due to an unused variable, has nothing to do with PR changes tho so we can ignore it right now.

**Comment by molleweide** [comment]
> > i don't understand why the check fails.
> 
> Checks are failing due to an unused variable, has nothing to do with PR changes tho so we can ignore it right now.

aight!

I would appreciate if you and connor can check if this one works, i am getting errors when trying to run the `next` branch so I am not sure. BUT this should follow previous patterns so in any case this should at least lay some of the groundwork.

**Comment by molleweide** [comment]
hmm after having checkout `next` branch and then switching back to my main branch which is a couple days older I get errors like these:

```vim
Error detected while processing /Users/hjalmarjakobsson/.local/share/nvim/site/pack/packer/start/playground/plugin/nvim-treesitter-playground.lua:
E5113: Error while calling lua chunk: ...r/start/playground/plugin/nvim-treesitter-playground.lua:16: attempt to call field 'nvim_create_user_command'
(a nil value)
stack traceback:
        ...r/start/playground/plugin/nvim-treesitter-playground.lua:16: in main chunk
E5113: Error while calling lua chunk: ...r/start/playground/plugin/nvim-treesitter-playground.lua:16: attempt to call field 'nvim_create_user_command'
(a nil value)
stack traceback:
        ...r/start/playground/plugin/nvim-treesitter-playground.lua:16: in main chunk
Error executing vim.schedule lua callback: /Users/hjalmarjakobsson/.config/nvim/init.lua:31: Vim:E492: Not an editor command: Dashboard
stack traceback:
        [C]: in function 'cmd'
        /Users/hjalmarjakobsson/.config/nvim/init.lua:31: in function 'fn'
        vim.lua:415: in function 'cb'
        vim.lua:285: in function <vim.lua:285>
[doom] [WARN  05:13:06] [string "..."]:0: doom-treesitter:  clang has poor compatibility compiling treesitter parsers.  We recommend using gcc, see iss
ue #246 for details.  (https://github.com/NTBBloodbath/doom-nvim/issues/246)
[doom] [WARN  05:13:30] init.lua:162: reloader: If you made changes to the config of a plugin, run `:PackerCompile` to execute these changes.
E5108: Error executing lua .../pack/packer/start/which-key.nvim/lua/which-key/view.lua:53: Vim(lua):E5108: Error executing lua ...t/playground/lua/nvim
-treesitter-playground/internal.lua:45: attempt to call field 'nvim_create_augroup' (a nil value)
stack traceback:
        ...t/playground/lua/nvim-treesitter-playground/internal.lua:45: in main chunk
        [C]: in function 'resolve_module'
        ...er/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:467: in function 'detach_module'
        ...er/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:481: in function 'reattach_module'
        [string ":lua"]:1: in main chunk
        [C]: in function 'nvim_buf_set_option'
        .../pack/packer/start/which-key.nvim/lua/which-key/view.lua:53: in function 'show'
        .../pack/packer/start/which-key.nvim/lua/which-key/view.lua:276: in function 'on_keys'
        .../pack/packer/start/which-key.nvim/lua/which-key/view.lua:240: in function 'open'
        .../pack/packer/start/which-key.nvim/lua/which-key/init.lua:51: in function 'show'
        [string ":lua"]:1: in main chunk
stack traceback:
        [C]: in function 'nvim_buf_set_option'
        .../pack/packer/start/which-key.nvim/lua/which-key/view.lua:53: in function 'show'
        .../pack/packer/start/which-key.nvim/lua/which-key/view.lua:276: in function 'on_keys'
        .../pack/packer/start/which-key.nvim/lua/which-key/view.lua:240: in function 'open'
        .../pack/packer/start/which-key.nvim/lua/which-key/init.lua:51: in function 'show'
        [string ":lua"]:1: in main chunk
E492: Not an editor command: Telescope find_files
E492: Not an editor command: Telescope find_files
E492: Not an editor command: Telescope find_files
E492: Not an editor command: Telescope find_files
E492: Not an editor command: Telescope find_files
```

**Comment by molleweide** [comment]
I added my `plugins_reloader`. it checks which specs are using local clone and then adds a dedicated plenary.reload autocmd to each plugin.

**Comment by connorgmeehan** [comment]
Can you remove the plugins_reloader changes and put that in a seperate PR?  It's best to change one thing at a time.  Also those errors are to be expected when switching between branches, usually it just needs a `:PackerCompile` -> restart nvim to solve.

**Comment by molleweide** [comment]
Haha yeah ill rm it

**Comment by molleweide** [comment]
> Also those errors are to be expected when switching between branches, usually it just needs a `:PackerCompile` -> restart nvim to solve.

yes I know but this did not work on my first tries so I am not sure yet..

**Comment by molleweide** [comment]
dropped commits.

**Comment by molleweide** [comment]
now we need to get keybinds to reload so that eq. you can override the esc seq live

**Comment by molleweide** [comment]
i also tested this was mergable with the latest next again.

**Comment by molleweide** [comment]
@connorgmeehan 

SUGGESTION: keep only a single table for `settings.lua` table in the config root and remove the core settings table that is implemented in `core/globals.lua`.

Arguments for this would be that we specify clear default values which would make the core settings table redundant, ie. it would be easier to maintain and also be more explicit to the user. 

Are there any arguments against this in your view?

Also, I shall merge latest next into this branch and make sure this is up to date again.

**Pull request closed without merging**
