### PR TITLE
Feature: restructure modules and config

### LINKED ISSUE #233: Feature Proposal: New module architecture
I posted on the discord discussing ways for laying out a new, more modular architecture for modules in doom-nvim.  This issue's goal is to propose how it might work and get feedback so we land on a good solution.  Feel free to provide feedback to any part of this proposal.  I will also use block quotes for areas that I'm looking for feedback.

**This is just to get the discussion started, we should start on the implementation once doom-nvim 3.2 is released.**

# Overview

Each module in `doom_modules.lua` will have a config file determined by the module name i.e.: the `lsp` will have a `doom-lsp.lua` file.  This file will be responsible for importing all of its dependencies via `packer.use`, binding all of its keymaps, adding all of its autocommands and adding any additional logic, commands and handlers.

> I'm not sure if we should have a single file, such as `doom-lsp.lua`, or instead folders, `doom-lsp/init.lua` + `doom-lsp/config.lua`.  I like the idea of having it all in one file but if a module contains a lot of logic it could make it harder to maintain.  Having folders would also let us include a README.md for each module.  Would both work?

## Features and improvements
1. Easier to find code relating to a specific feature
2. Easier to manage modular architecture
3. Per module keymaps, only binds what's necessary.
4. Easier to configure LSPs, linters, documentation generators, code formatters per language
5. Add custom logic, commands, keymaps for specific languages

# Module API

Each module will return an object with certain properties, I think it's easiest to describe in lua.

```lua
local module = {}

-- USER SETTINGS
-- Settings related to a module (avoid changing down the line to reduce merge conflicts)
module.settings = {
  enable_some_functionality = false,
}

-- Custom configuration can be handled by a function 
local config = function()
  if settings.enable_some_functionality then
  end
  ...
end

-- IMPORTING DEPENDENCIES
-- I think it's best not to abstract libraries that people are used to, 
-- For this reason we just pass the packer use function into the module
module.packer = function(use)
  use({
    'nvim-treesitter/nvim-treesitter',
    config = config,
  })
end

-- BINDING KEYMAPS
-- Keymaps can be defined in an object, this should integrate with whichkey and nvim-mapper
-- Again, using familiar technologies feels like the best path to me and nest.nvim seems to be the most popular library to setup keymaps
-- We could also disable keymaps by creating new flags in doom_modules.lua such as +no_keymap
-- This could also be used to generate documentation or create a cheatsheet down the line
module.keymaps = {
  ...
}
return module
```

> Are there any other features that should be standardized across modules?

> Would we need a `user_keymaps` in case users wanted to add or edit existing keymaps (and would this be able to unbind the defaults?)  

# Language Module API

While some languages work great with the `nvim-lspconfig` defaults, others require a larger amount of customisability.  For this reason I think languages should optionally have their own modules that fallback to sane defaults. 

```lua
local module = {}

-- LSPS
-- Defines all the necessary LSPs for this language module
-- The key or ipairs value is used to automatically download the LSP via nvim-lspmanager
module.language_servers = {
  volar = {
    -- ... custom config to be passed into the language server
    -- This config 
  },
  'tailwindcss', -- LSP without custom config
}

-- LINTERS
-- Defines the linters for this language
module.linters = {
  'eslint',
}

-- DOCUMENTATION_GENERATORS
-- Documentation generator and configs possibly via neogen https://github.com/danymat/neogen
module.documentation_generators = {
  -- ...
}

-- FORMATTERS
-- Same as above
module.formatters = {
  'prettier',
}

-- Same behaviours as a regular module
local module.keymaps = {
  .. custom language feature
}
```

> There are some instances where we need to configure multiple of the same LSP such as in the case of volar: https://github.com/johnsoncodehk/volar/discussions/606
> How could we include this behaviour? One solution could be

```lua
module.language_servers = {
  -- language server name to install
  volar = {
    -- Name of 1st instance
    volar_api = {
      -- 1st instance config
    },
    -- Name of 2nd instance
    volar_doc = {
      -- 2nd instance config
    },
  }
}
```

### Doom config

We'll need a way of passing relevant doom_config options to these modules i.e. `freeze_dependencies` (disables pinned packer dependencies in `/dev`).  This could be passed into the `module.packer` function: 
```lua
module.packer = function(use, doom_config)
  if doom_config.freeze_depencies then
    ...
  end
end
```
We will also need a way to pass this into the `config` function of the packer dependency.

### PR DESCRIPTION
**Pull request by LuigiPiucco**
For more info on this, see #233 and the commit messages, but essentially this separates concerns about the various functionalities: each module has its directory, toggling a module just entails listing it in `doom-nvim/modules.lua`, everything else can be overridden and configured in `doom-nvim/config.lua`. Packages can be added per module (in a `packages.lua` file) or by the user in the `doom.packages` table, they can also override module packages however desired.
The config files changed names as well, the `doom_` prefix was removed, for simplicity, and we have the luxury of changing this because the old files wouldn't work anyway.

These are big, breaking changes, which will be documented in later work. The next big thing to do here is add a README.md per module explaining all options, bindings and autocmds, plus whatever extra things they enable. Another extra piece of work is to create LSP wrapper for each language, with appropriate packages and config. Also, doom.norg should probably be rewritten, I imagine most of it is outdated now.

Also, I'd like to thank @connorgmeehan, @caligian and @NTBBloodbath for support and ideas.

Closes #233 #251
(and probably many others, but I'll list only direct fixes)

### CODE REVIEW

**Comment by LuigiPiucco** [comment]
The linter and style checker should be pleased now.

**Comment by connorgmeehan** [comment]
Hey sorry for the delay reviewing, getting around to it now.  These are some smaller issues I found on a first read through.  Before I get more into it I just want to confirm I understand how everything works and make sure I fully understand the lifecycle of a module.  I'll write my understanding below, could you confirm if I'm right or correct me if I'm wrong?

By the way, some really cool optimisations here, it's awesome to see.

First `doom.config.core`'s `load function is called which:
   1. Set's default vim options, loads default config options
   2. populates `doom` global object with empty tables for `autocommands`, `binds`, 
   3. Loads each enabled module and adds packer dependencies to `packages` table and settings to the `doom` object.
   4. Executes the user's config.lua file allowing the user to override/modify settings.
   5. Loads and populates `autocommands` and `binds

Then `doom/core/init` is loaded, just applies various settings, for colourschemes, sets up some commands etc.

Then `doom/modules/init`
1. Packer is initialised
2. All of the packer config functions are flattened into a table.
3. We iterate along the packer dependencies (from doom.config.core) and merge the packer spec with the relevant packer config function.
    a. Can the user can provide a `post config` hook to packages by setting the `config` field of the packer spec in `config.lua`?
4.  Autocommands are iterated upon and built.

**Comment by LuigiPiucco** [comment]
>  I'll write my understanding below, could you confirm if I'm right or correct me if I'm wrong?

That's correct, the only mistake in the explanation is a typo in the module name (it's `doom.core.config`).

> a. Can the user can provide a post config hook to packages by setting the config field of the packer spec in config.lua?

Yes and, in fact, it's done automatically if the user tries to override config in `doom.packages[package]` spec. That's why config is separated from `packages.lua` into `init.lua`. `doom/modules/init.lua` passes to packer both what's in `doom.packages[package].config` (this is the user override, or post config, if you will) and what's in the flattened table of configs acquired from iterating the `init.lua`s of each module (this is the built-in config, and it's run first).

The exact method for running the two of them is simple, even though it took me a while to figure out. I first tried to create an anonymous function that just runs both in sequence, but them I ran into a packer issue that prohibits from having captures in config. I hit my head on the wall for a while, until I discovered that passing both functions in a table works, even though its undocumented.

**Comment by connorgmeehan** [comment]
Ok, I noticed you implemented the lua language using a `config.lua` file in the module.  Could you point out where it's being executed from and when in the lifecycle it occurs?

**Comment by LuigiPiucco** [comment]
In `doom/modules/lua`, there is an autocmd to run `dofile` on `config.lua` upon entering a lua file. It's a once command, and is meant to run things like `require("lspconfig")[server].setup()`, lsp/dap install commands (if the autoinstall module is on) and treesitter parser configs.

I made an exception for the installation of treesitter parsers, they don't need the autoinstall module, because they aren't packaged in distros, at least that I know of. Additionally, the module breaks lsp and dap on NixOS, since the downloaded executables don't work on NixOS. An alternative solution would be to add three autoinstall modules, one for each of lsp, dap and treesitter.

**Comment by connorgmeehan** [comment]
It looks like there are some issues with inter-module dependencies (`lsp` depends on `snippets`, `autoinstall` depends on `dap`).  Additionally I think the way you override a modules defaults can be improved.  I have some changes to the order of execution that I think would solve all of this.

Firstly I think the enabled modules should be available before parsing the `packages.lua` of each module.  That way the `auto_install` module can disable `dap-install` if `dap` is not enabled.

Secondly I think all overrides should be editable the same, logical way.  I think autocommands, packer specs, keybinds, configure function should be under the same `doom.module.module_name` object allowing the user to do something as follows:
```lua
local lsp_module` = doom.modules.lsp
lsp_module.packages['lspconfig'].commit = '...'
lsp_module.keybinds = {...}
tbl.insert(lsp_module.autocmds, { ... })
```

Lastly I think this `doom.modules.lsp` object should be populated, including the autocommands, packer spec, keybinds etc, before the `config.lua` is parsed.  I know that this means we have to iterate over the same data twice and isn't as efficient but I think there's huge value for newcomers to able to `print(vim.inspect(lsp_module.keybinds))` and see a valid config.  Looking at the source code of a module to see what kind of data it returns isn't always super clear, especially for someone new to nvim.

This is just one possible solution and I'm interested in hearing alternatives to either of these issues.  I think that this new architecture needs to be a bit clearer in how it functions and I think these changes would make a very clear mental modal of:
1. Parse `modules.lua`
2. Populate defaults in `doom` object
3. Allow user to inspect and override defaults via `config.lua`
4. Start doom-nvim.

**Comment by connorgmeehan** [comment]
I've branched off your changes [here](https://github.com/connorgmeehan/doom-nvim/tree/custom-module-architecture) and I've pushed some fixes to some of the issues outlined here.  Feel free to cherry pick into this PR.  I'd like to get this PR to a point where I can use it for work.

**Comment by LuigiPiucco** [comment]
> It looks like there are some issues with inter-module dependencies (`lsp` depends on `snippets`, `autoinstall` depends on `dap`).

This is true and, because I had already opened the PR when I noticed, I left it there to allow you to review without stuff changing under your feet. However, I think the solution is even simpler: `is_plugin_disabled(module_name)` works everywhere, since it doesn't depend on the doom global, instead it checks the `modules.lua` file directly. As such, we can use it to require packages conditionally based on whether a module has been enabled. So this bit is probably not needed, or rather, it's already satisfied:

> Firstly I think the enabled modules should be available before parsing the `packages.lua` of each module.

---

> Secondly I think all overrides should be editable the same, logical way. I think autocommands, packer specs, keybinds, configure function should be under the same `doom.module.module_name` object

This is more of a stylistic choice, and while it does look a bit better, it incurs iteration cost and complexity. I can do it, but it would be a big force-push, since all the module looping would change. I will let us discuss some more before tackling this.

---

> Lastly I think this `doom.modules.lsp` object should be populated, including the autocommands, packer spec, keybinds etc, before the `config.lua` is parsed. I know that this means we have to iterate over the same data twice and isn't as efficient

I don't think this is doable, not because of efficiency, but because we need `doom` do be overridden before keybinds and autocmds can be added, since some of them are conditional. At best, we could populate these two based on defaults first, but since the user may change them, it would not reflect what actually ends up being the config.

> I think there's huge value for newcomers to able to `print(vim.inspect(lsp_module.keybinds))` and see a valid config.

It is certainly valuable, but I'm assuming here you mean adding a print in `config.lua`? If so, this is not doable, or rather, it is doable but the print will show the current state of `doom`, which may very well be changed later and is probably not what the user wants. We should instead direct them to run the command `:lua print(vim.inspect(doom.keybinds))` or the like, once they've gotten into doom, because then they can be sure of the final config. We may even add that as a bind.

---

> I think that this new architecture needs to be a bit clearer in how it functions

Yes, I've come to this conclusion as well, and I'm now thinking if I should add a documentation commit in this PR instead of saving it for later. I may push it along with the other stuff.

---

> I've branched off your changes [here](https://github.com/connorgmeehan/doom-nvim/tree/custom-module-architecture)

Most of these look great (I've not looked at the temp and lang ones yet), I can add them once I push with the other changes mentioned.

**Comment by connorgmeehan** [comment]
I think it's best not to rebase from here on out just to maintain the commit messages and show the changes a little clearer.  The only reason we'd want to rebase is to keep semantic commits but for such a large change I think it's better we just write the changelog ourselves.

> (Regarding inter-module dependencies)

Oh great! I had a go fixing some of these but ran into some errors.  Might have another go soon.

> This is more of a stylistic choice...discuss later

Yep that sounds good

> I don't think this is doable, not because of efficiency, but because we need doom do be overridden before keybinds and autocmds can be added, since some of them are conditional. At best, we could populate these two based on defaults first, but since the user may change them, it would not reflect what actually ends up being the config.

Ahhh that is a problem, the only conditional binds are in `modules/core/binds.lua` and `modules/core/autocmds.lua` right?  Maybe there's a way we can resolve that.
> it would not reflect what actually ends up being the config

I think that's ok because users will be modifying the same data that they're vim.inspecting.  I think it will still be clear to the user because they're changing the data and they control the order of execution.
```lua
print(vim.inspect(doom.modules.lsp.binds)) -- Initial config
doom.module.lsp.binds = { ... custom binds ... }
print(vim.inspect(doom.modules.lsp.binds)) -- Modified config
```

Another option could be a telescope view that allows users to search through current module configs and open the vim.inspected data in a new buffer.  Maybe it could even prepend the data with the code required to set the data, like if you telescoped for `telescope keybinds` you'd get.
```lua
-- This shows the current keybind settings for the telescope module.
-- Copy and paste this into your `config.lua` file to modify these.
doom.modules.telescope.keybinds = {
    -- <default keybinds>
}
```

> Yes, I've come to this conclusion as well, and I'm now thinking if I should add a documentation commit in this PR instead of saving it for later. I may push it along with the other stuff.

Yeah would love to see some documentation, might even help me with my understanding of how everything works.  I think short clear documentation is indicative of a logical, good API so the documentation will probably also help us make API decisions.  If you do a first pass I can come in and edit this documentation as well :).

**Review by NTBBloodbath — APPROVED** [review]

**Comment by NextAlone** [comment]
Will this be merged? Looking forward to these changes

**Comment by connorgmeehan** [comment]
Hey NextAlone, I have been expanding on these changes, adding language support, fixing bugs and writing documentation and I should be merging to `origin/next` soon.  I know it's been quite a delay but once this is done development should continue as normal.

**Comment by NextAlone** [comment]
> Hey NextAlone, I have been expanding on these changes, adding language support, fixing bugs and writing documentation and I should be merging to `origin/next` soon. I know it's been quite a delay but once this is done development should continue as normal.
> 
> The PR is here but it's a bit out of date (I just did some major refactoring to simplify the internal workings) #313
> 
> I will merge my changes, do some optimisations (addressing long packer sequencing time) make sure the documentation is good and then release it. Can I ask for some feedback on the documentation later on?

Ok, you can, and it works fine

**Pull request merged**
